name: Build Image from develop

on: 
  push:
    branches: 
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login --user tommysolsen -p $PASSWORD 
        docker build . --file Dockerfile --tag mpsyt/mps_youtube:develop
        docker push mpsyt/mps_youtube:develop
      env:
        PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
